---
defaults:
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH != $CI_PROJECT_PATH && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "bootc-org/fedora-bootc/base-images-experimental"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - when: never
  stage: build

include:
  - remote: https://gitlab.com/platform-engineering-org/gitlab-ci/-/raw/main/templates/build-image.gitlab-ci.yml # yamllint disable-line rule:line-length

stages:
  - build

.build-image-arch:
  parallel:
    matrix:
      - VARIANT:
          - minimal
          - full
        VERSION:
          - "40"
          - rawhide
  variables:
    IMAGE: $CI_REGISTRY_IMAGE-$VARIANT:$VERSION-$ARCH
    EXTRA_ARGS: --format oci --arch $ARCH --security-opt=label=disable --cap-add=all
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - !reference [.build-image, script]
    - buildah push $IMAGE
  extends: .build-image

build-amd64:
  variables:
    ARCH: amd64
  extends: .build-push-image-arch

build-arm64:
  tags:
    - platform-engineering
  variables:
    ARCH: arm64
  extends: .build-push-image-arch

manifests_list:
  parallel:
    matrix:
      - VARIANT:
          - minimal
          - full
        VERSION:
          - "40"
          - rawhide
  needs:
    - build-amd64
    - build-arm64
  image: quay.io/buildah/stable:v1.35.3
  variables:
    IMAGE: $CI_REGISTRY_IMAGE-$VARIANT:$VERSION
  before_script:
    - buildah login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah pull $IMAGE-arm64
    - buildah pull $IMAGE-amd64
  script:
    - buildah manifest create $IMAGE $IMAGE-amd64 $IMAGE-arm64
    - buildah manifest annotate $IMAGE $IMAGE-arm64 --os linux --arch arm64
    - buildah manifest annotate $IMAGE $IMAGE-amd64 --os linux --arch amd64
    - buildah manifest push  --all $IMAGE docker://$IMAGE
