# Configuration for bootc
postprocess:
  # XFS is our default filesystem
  - |
    #!/usr/bin/env bash
    mkdir -p /usr/lib/bootc/install/
    cat > /usr/lib/bootc/install/20-rhel.toml << EOF
    [install]
    root-fs-type = "xfs"
    EOF
