# This metadata goes unused. We are just reusing the .spec file format as a way
# to declare requirements basically. Note that everything here must be
# BuildRequires as we use `dnf builddep` to install things.
Name:           fedora-kinoite
Version:        0
Release:        0
Summary:        Base image
License:        ASL 2.0

BuildRequires: NetworkManager
BuildRequires: NetworkManager-bluetooth
Buildrequires: wget
BuildRequires: NetworkManager-config-connectivity-fedora
BuildRequires: NetworkManager-ppp
BuildRequires: NetworkManager-wifi
BuildRequires: NetworkManager-wwan
BuildRequires: acl
BuildRequires: adwaita-gtk2-theme
BuildRequires: akonadi-server
BuildRequires: akonadi-server-mysql
BuildRequires: alsa-sof-firmware
BuildRequires: alsa-ucm
BuildRequires: alsa-utils
BuildRequires: amd-gpu-firmware
BuildRequires: amd-ucode-firmware
BuildRequires: ark
BuildRequires: at-spi2-atk
BuildRequires: at-spi2-core
BuildRequires: atheros-firmware
BuildRequires: attr
BuildRequires: audit
BuildRequires: b43-fwcutter
BuildRequires: b43-openfwwf
BuildRequires: basesystem
BuildRequires: bash
BuildRequires: bash-color-prompt
BuildRequires: bash-completion
BuildRequires: bc
BuildRequires: bcache-tools
BuildRequires: bind-utils
BuildRequires: bluedevil
BuildRequires: bluez-cups
BuildRequires: brcmfmac-firmware
BuildRequires: breeze-icon-theme
BuildRequires: brltty
BuildRequires: btrfs-progs
BuildRequires: buildah
BuildRequires: bzip2
BuildRequires: chrony
BuildRequires: cifs-utils
BuildRequires: cirrus-audio-firmware
BuildRequires: colord
BuildRequires: compsize
BuildRequires: coreutils
BuildRequires: cpio
BuildRequires: cryptsetup
BuildRequires: cups
BuildRequires: cups-browsed
BuildRequires: cups-filters
BuildRequires: curl
BuildRequires: cyrus-sasl-plain
BuildRequires: default-editor
BuildRequires: default-fonts-cjk-mono
BuildRequires: default-fonts-cjk-sans
BuildRequires: default-fonts-cjk-serif
BuildRequires: default-fonts-core-emoji
BuildRequires: default-fonts-core-math
BuildRequires: default-fonts-core-mono
BuildRequires: default-fonts-core-sans
BuildRequires: default-fonts-core-serif
BuildRequires: default-fonts-other-mono
BuildRequires: default-fonts-other-sans
BuildRequires: default-fonts-other-serif
BuildRequires: dhcp-client
BuildRequires: dmraid
BuildRequires: dnsmasq
BuildRequires: dolphin
BuildRequires: e2fsprogs
BuildRequires: efibootmgr
BuildRequires: ethtool
BuildRequires: exfatprogs
BuildRequires: fedora-bookmarks
BuildRequires: fedora-chromium-config
BuildRequires: fedora-flathub-remote
BuildRequires: fedora-repos-archive
BuildRequires: fedora-repos-ostree
BuildRequires: fedora-workstation-backgrounds
BuildRequires: fedora-workstation-repositories
BuildRequires: ffmpegthumbs
BuildRequires: file
BuildRequires: filelight
BuildRequires: filesystem
BuildRequires: firewall-config
BuildRequires: firewalld
BuildRequires: flatpak
BuildRequires: flatpak-kcm
BuildRequires: fpaste
BuildRequires: fprintd-pam
BuildRequires: fros-gnome
BuildRequires: fwupd
BuildRequires: gamemode
BuildRequires: gdb
BuildRequires: git-core
BuildRequires: git-core-doc
BuildRequires: glibc
BuildRequires: glibc-all-langpacks
BuildRequires: gnome-keyring-pam
BuildRequires: gnupg2
BuildRequires: grub2-efi-ia32
BuildRequires: grub2-efi-x64
BuildRequires: grub2-pc
BuildRequires: gstreamer1-plugin-libav
BuildRequires: gstreamer1-plugins-bad-free
BuildRequires: gstreamer1-plugins-good
BuildRequires: gstreamer1-plugins-ugly-free
BuildRequires: gutenprint
BuildRequires: gutenprint-cups
BuildRequires: hfsplus-tools
BuildRequires: hostname
BuildRequires: hplip
BuildRequires: hunspell
BuildRequires: hyperv-daemons
BuildRequires: ibus-anthy
BuildRequires: ibus-gtk3
BuildRequires: ibus-gtk4
BuildRequires: ibus-hangul
BuildRequires: ibus-libpinyin
BuildRequires: ibus-libzhuyin
BuildRequires: ibus-m17n
BuildRequires: ibus-typing-booster
BuildRequires: intel-audio-firmware
BuildRequires: intel-gpu-firmware
BuildRequires: iproute
BuildRequires: iptables-nft
BuildRequires: iptstate
BuildRequires: iputils
BuildRequires: iwlegacy-firmware
BuildRequires: iwlwifi-dvm-firmware
BuildRequires: iwlwifi-mvm-firmware
BuildRequires: kbd
BuildRequires: kernel
BuildRequires: kernel-modules
BuildRequires: kernel-modules-extra
BuildRequires: langpacks-en
BuildRequires: less
BuildRequires: libappindicator-gtk3
BuildRequires: libertas-firmware
BuildRequires: libglvnd-gles
BuildRequires: libva-intel-media-driver
BuildRequires: linux-firmware
BuildRequires: logrotate
BuildRequires: lrzsz
BuildRequires: lsof
BuildRequires: lvm2
BuildRequires: man-db
BuildRequires: man-pages
BuildRequires: mcelog
BuildRequires: mdadm
BuildRequires: mesa-dri-drivers
BuildRequires: mesa-vulkan-drivers
BuildRequires: microcode_ctl
BuildRequires: mobile-broadband-provider-info
BuildRequires: mpage
BuildRequires: mt7xxx-firmware
BuildRequires: mtr
BuildRequires: ncurses
BuildRequires: nfs-utils
BuildRequires: nss-altfiles
BuildRequires: nss-mdns
BuildRequires: ntfs-3g
BuildRequires: ntfsprogs
BuildRequires: nvidia-gpu-firmware
BuildRequires: nxpwireless-firmware
BuildRequires: open-vm-tools-desktop
BuildRequires: opensc
BuildRequires: openssh-clients
BuildRequires: openssh-server
BuildRequires: orca
BuildRequires: ostree-grub2
BuildRequires: pam_afs_session
BuildRequires: paps
BuildRequires: passwdqc
BuildRequires: pciutils
BuildRequires: phonon-qt6-backend-vlc
BuildRequires: pinentry-qt
BuildRequires: pinfo
BuildRequires: pipewire-alsa
BuildRequires: pipewire-gstreamer
BuildRequires: pipewire-pulseaudio
BuildRequires: pipewire-utils
BuildRequires: plocate
BuildRequires: plymouth
BuildRequires: plymouth-system-theme
BuildRequires: podman
BuildRequires: policycoreutils
BuildRequires: policycoreutils-python-utils
BuildRequires: procps-ng
BuildRequires: psmisc
BuildRequires: qemu-guest-agent
BuildRequires: quota
BuildRequires: realmd
BuildRequires: realtek-firmware
BuildRequires: rootfiles
BuildRequires: rpm
BuildRequires: rpm-ostree
BuildRequires: rsync
BuildRequires: samba-client
BuildRequires: selinux-policy-targeted
BuildRequires: setup
BuildRequires: shadow-utils
BuildRequires: shim-ia32
BuildRequires: shim-x64
BuildRequires: skopeo
BuildRequires: slirp4netns
BuildRequires: sos
BuildRequires: spectacle
BuildRequires: speech-dispatcher
BuildRequires: spice-vdagent
BuildRequires: spice-webdavd
BuildRequires: sssd-common
BuildRequires: sssd-kcm
BuildRequires: sudo
BuildRequires: system-config-printer-udev
BuildRequires: systemd
BuildRequires: systemd-container
BuildRequires: systemd-oomd-defaults
BuildRequires: systemd-resolved
BuildRequires: systemd-udev
BuildRequires: tar
BuildRequires: thermald
BuildRequires: time
BuildRequires: tiwilink-firmware
BuildRequires: toolbox
BuildRequires: tree
BuildRequires: udisks2
BuildRequires: unzip
BuildRequires: uresourced
BuildRequires: usb_modeswitch
BuildRequires: usbutils
BuildRequires: util-linux
BuildRequires: vim-minimal
BuildRequires: virtualbox-guest-additions
BuildRequires: vlc-plugin-gstreamer
BuildRequires: vulkan-tools
BuildRequires: wget2-wget
BuildRequires: which
BuildRequires: whois
BuildRequires: wireplumber
BuildRequires: words
BuildRequires: wpa_supplicant
BuildRequires: xdg-desktop-portal
BuildRequires: xdpyinfo
BuildRequires: xwaylandvideobridge
BuildRequires: zip
BuildRequires: zram-generator-defaults
BuildRequires: cosmic-desktop

%description
%{summary}
